/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package care;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SAIF
 */
public class DisabilityPage1 extends javax.swing.JFrame {

    /**
     * Creates new form DisabilityPage
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
     String user;
    public DisabilityPage1() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jTable1.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(String.class)).setBackground(new Color(0,0,0,0));
        
        jTable1.setGridColor(Color.WHITE);
        jTable1.setForeground(Color.WHITE);
        
        disabilityfield.setBackground(new Color(0,0,0,0));
        
        disabilityfield.setOpaque(false);
         jTable1.setOpaque(false);
            ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(String.class)).setOpaque(false);
            
        disabilityfield.getViewport().setOpaque(false);
        
        jTable1.setShowGrid(true);
       
        
        jTable1.setRowHeight(50);  //set rows height
        
      //  jTable1.setRowHeight(2,70);//sets height of a specific row
        
//sets column width
        TableColumnModel columnModel = jTable1.getColumnModel();
        TableModel model = jTable1.getModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(180);
        columnModel.getColumn(2).setPreferredWidth(3);
        columnModel.getColumn(3).setPreferredWidth(150);
        columnModel.getColumn(4).setPreferredWidth(20);
        columnModel.getColumn(5).setPreferredWidth(5);
        show_info();
        
   }

    public DisabilityPage1(String username){
        this.user = username;
        initComponents();
        this.setLocationRelativeTo(null);
        
        jTable1.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(String.class)).setBackground(new Color(0,0,0,0));
        
        jTable1.setGridColor(Color.WHITE);
        jTable1.setForeground(Color.WHITE);
        
        disabilityfield.setBackground(new Color(0,0,0,0));
        
        disabilityfield.setOpaque(false);
         jTable1.setOpaque(false);
            ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(String.class)).setOpaque(false);
            
        disabilityfield.getViewport().setOpaque(false);
        
        jTable1.setShowGrid(true);
       
        
        jTable1.setRowHeight(50);  //set rows height
        
      //  jTable1.setRowHeight(2,70);//sets height of a specific row
        
//sets column width
        TableColumnModel columnModel = jTable1.getColumnModel();
        TableModel model = jTable1.getModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(180);
        columnModel.getColumn(2).setPreferredWidth(3);
        columnModel.getColumn(3).setPreferredWidth(150);
        columnModel.getColumn(4).setPreferredWidth(20);
        columnModel.getColumn(5).setPreferredWidth(5);
        show_info();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        homebutton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        barpannel = new javax.swing.JPanel();
        disabilityfield = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backbutton = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        searchbox = new javax.swing.JTextField();
        background1 = new javax.swing.JLabel();

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\background_light_blur_68629_1920x1080.jpg")); // NOI18N
        background.setText("background");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        homebutton.setForeground(new java.awt.Color(0, 102, 153));
        homebutton.setText("HOME");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(homebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        title.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("CARE  FOR  THE  SPECIAL  PEOPLE");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 670, 60));

        minimize.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        minimize.setForeground(new java.awt.Color(153, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.setToolTipText("");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, 20));

        exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(153, 255, 255));
        exit.setText("x");
        exit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, 30));

        barpannel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout barpannelLayout = new javax.swing.GroupLayout(barpannel);
        barpannel.setLayout(barpannelLayout);
        barpannelLayout.setHorizontalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        barpannelLayout.setVerticalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(barpannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DISABILITY NAME", "SYMPTOMS", "CURABLE", "COMMUNICATION SKILL", "DEPARTMENT", "PREFERABLE DOCTOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        disabilityfield.setViewportView(jTable1);

        getContentPane().add(disabilityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 890, 430));

        backbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backbutton.setForeground(new java.awt.Color(0, 102, 153));
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, -1, -1));

        searchbutton.setBackground(new java.awt.Color(204, 204, 255));
        searchbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(0, 102, 153));
        searchbutton.setText("SEARCH");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, -1, -1));

        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });
        getContentPane().add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 250, -1));

        background1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\background_light_blur_68629_1920x1080.jpg")); // NOI18N
        background1.setText("background");
        background1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                background1KeyReleased(evt);
            }
        });
        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public ArrayList<DisabilityInfo> disabilityList(){
        ArrayList<DisabilityInfo> disabilitiesList = new ArrayList<>();
         conn = DatabaseHandler.connectDatabase1();
         try{
             String query = "SELECT * FROM disabilities";
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(query);
             DisabilityInfo info;
             while(rs.next()){
                 info = new DisabilityInfo(rs.getString("disability"),rs.getString("symptoms"),rs.getString("curable"),rs.getString("communication"),rs.getString("department"),rs.getString("doctor"));
                 disabilitiesList.add(info);
             }
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
         return disabilitiesList;
    }
    
    public void show_info(){
        ArrayList<DisabilityInfo> list = disabilityList();
        DefaultTableModel model  = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[6];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getdisability();
            row[1] = list.get(i).getsymptoms();
            row[2] = list.get(i).getcurable();
            row[3] = list.get(i).getcommunication();
            row[4] = list.get(i).getdepartment();
            row[5] = list.get(i).getdoctor();
            model.addRow(row);
        }
    }
    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StartPage sp = new StartPage();
        sp.setVisible(true);
    }//GEN-LAST:event_homebuttonActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);// for minimize
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0); //for exit
    }//GEN-LAST:event_exitMouseClicked

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DoctorProfilePage ppp= new DoctorProfilePage(user);
        ppp.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
        
       /* try{
            String query = "SELECT * FROM disabilities WHERE disability = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1,searchbox.getText());
            ResultSet rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void background1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_background1KeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_background1KeyReleased

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        // TODO add your handling code here:
       /* try{
            String query = "SELECT disability,symptoms,curable,communication,department,doctor FROM disabilities WHERE disability = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1,searchbox.getText());
            ResultSet rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           // pst.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            String query = "SELECT disability,symptoms,curable,communication,department,doctor FROM disabilities WHERE department = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1,searchbox.getText());
            ResultSet rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           // pst.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }*/
       
       DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
       String search =searchbox.getText();
       TableRowSorter<DefaultTableModel> tr = new  TableRowSorter<DefaultTableModel>(table);
       jTable1.setRowSorter(tr);
       tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_searchboxKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisabilityPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisabilityPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisabilityPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisabilityPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisabilityPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JPanel barpannel;
    private javax.swing.JScrollPane disabilityfield;
    private javax.swing.JLabel exit;
    private javax.swing.JButton homebutton;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchbutton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
