/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package care;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author SAIF
 */
public class DoctorProfilePage extends javax.swing.JFrame {

    /**
     * Creates new form DoctorProfilePage
     */
     Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String user;
    public DoctorProfilePage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public DoctorProfilePage(String username){
        initComponents();
        this.setLocationRelativeTo(null);
        this.user=username;
            conn = DatabaseHandler.connectDatabase1();
        try{
            String sql ="SELECT * FROM doctor where username ='"+username+"'";
            pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
             String fn = rs.getString("first_name");
             namelabel.setText(fn);
             String gen = rs.getString("gender");
             genderlabel.setText(gen);
             String ag = rs.getString("birthdate");
             agelabel.setText(ag);

             String add = rs.getString("address");
             addresslabel.setText(add);
             String mob = rs.getString("mobile");
             mobilenolabel.setText(mob);
             
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);   
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homebutton = new javax.swing.JButton();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        barpannel = new javax.swing.JPanel();
        barpannel1 = new javax.swing.JPanel();
        patient = new javax.swing.JLabel();
        informationtitle = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        mobileno = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        gototitle = new javax.swing.JLabel();
        disabilitybutton = new javax.swing.JButton();
        patientbutton = new javax.swing.JButton();
        doctorbutton = new javax.swing.JButton();
        hospitalbutton = new javax.swing.JButton();
        opportunitybutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        gototitle1 = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        genderlabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        addresslabel = new javax.swing.JLabel();
        mobilenolabel = new javax.swing.JLabel();
        logoutbutton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        homebutton.setForeground(new java.awt.Color(0, 102, 153));
        homebutton.setText("HOME");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(homebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        minimize.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        minimize.setForeground(new java.awt.Color(153, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.setToolTipText("");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, 20));

        exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(153, 255, 255));
        exit.setText("x");
        exit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, 30));

        title.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("CARE  FOR  THE  SPECIAL  PEOPLE");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 670, 60));

        barpannel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout barpannelLayout = new javax.swing.GroupLayout(barpannel);
        barpannel.setLayout(barpannelLayout);
        barpannelLayout.setHorizontalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        barpannelLayout.setVerticalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(barpannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        barpannel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout barpannel1Layout = new javax.swing.GroupLayout(barpannel1);
        barpannel1.setLayout(barpannel1Layout);
        barpannel1Layout.setHorizontalGroup(
            barpannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        barpannel1Layout.setVerticalGroup(
            barpannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(barpannel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 10, 610));

        patient.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\IMG_4306.PNG")); // NOI18N
        patient.setText("patient");
        patient.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 100, -1));

        informationtitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        informationtitle.setForeground(new java.awt.Color(204, 204, 255));
        informationtitle.setText("DOCTOR INFORMATION");
        getContentPane().add(informationtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, -1));

        name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        name.setForeground(new java.awt.Color(204, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name.setText("NAME :");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 70, -1));

        gender.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        gender.setForeground(new java.awt.Color(204, 255, 255));
        gender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gender.setText("GENDER :");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        age.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        age.setForeground(new java.awt.Color(204, 255, 255));
        age.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        age.setText("AGE :");
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 50, -1));

        address.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        address.setForeground(new java.awt.Color(204, 255, 255));
        address.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        address.setText("ADDRESS :");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 90, -1));

        mobileno.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mobileno.setForeground(new java.awt.Color(204, 255, 255));
        mobileno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mobileno.setText("MOBILE NO :");
        getContentPane().add(mobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 110, -1));

        backbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backbutton.setForeground(new java.awt.Color(0, 102, 153));
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 100, -1));

        gototitle.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        gototitle.setForeground(new java.awt.Color(204, 255, 204));
        gototitle.setText("GO TO");
        getContentPane().add(gototitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 90, 20));

        disabilitybutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        disabilitybutton.setForeground(new java.awt.Color(0, 102, 153));
        disabilitybutton.setText("DISABILITY");
        disabilitybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilitybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(disabilitybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 180, -1));

        patientbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        patientbutton.setForeground(new java.awt.Color(0, 102, 153));
        patientbutton.setText("PATIENTS");
        patientbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(patientbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 180, -1));

        doctorbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        doctorbutton.setForeground(new java.awt.Color(0, 102, 153));
        doctorbutton.setText("DOCTOR");
        doctorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(doctorbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 180, -1));

        hospitalbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hospitalbutton.setForeground(new java.awt.Color(0, 102, 153));
        hospitalbutton.setText("HOSPITAL");
        hospitalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(hospitalbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 180, -1));

        opportunitybutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        opportunitybutton.setForeground(new java.awt.Color(0, 102, 153));
        opportunitybutton.setText("OPPORTUNITY");
        opportunitybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opportunitybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(opportunitybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 180, -1));

        updatebutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        updatebutton.setForeground(new java.awt.Color(0, 102, 153));
        updatebutton.setText("UPDATE");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 100, -1));

        gototitle1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        gototitle1.setForeground(new java.awt.Color(204, 255, 204));
        gototitle1.setText("GO TO");
        getContentPane().add(gototitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 90, 20));

        namelabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 260, 20));

        genderlabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        genderlabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(genderlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 260, 20));

        agelabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        agelabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(agelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 260, 20));

        addresslabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addresslabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(addresslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 260, 20));

        mobilenolabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mobilenolabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(mobilenolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 260, 20));

        logoutbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        logoutbutton.setForeground(new java.awt.Color(0, 102, 153));
        logoutbutton.setText("SIGN OUT");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 710, 120, -1));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\background_light_blur_68629_1920x1080.jpg")); // NOI18N
        background.setText("background");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StartPage sp = new StartPage();
        sp.setVisible(true);
    }//GEN-LAST:event_homebuttonActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);// for minimize
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0); //for exit
    }//GEN-LAST:event_exitMouseClicked

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DoctorSignInPage dsp= new DoctorSignInPage();
        dsp.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void disabilitybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilitybuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DisabilityPage1 disp = new DisabilityPage1(user);
        disp.setVisible(true);
    }//GEN-LAST:event_disabilitybuttonActionPerformed

    private void patientbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientbuttonActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
    }//GEN-LAST:event_patientbuttonActionPerformed

    private void doctorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorbuttonActionPerformed

    private void hospitalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HospitalPage hp = new HospitalPage(user);
        hp.setVisible(true);
    }//GEN-LAST:event_hospitalbuttonActionPerformed

    private void opportunitybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opportunitybuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        OpportunityPage op = new OpportunityPage(user);
        op.setVisible(true);
    }//GEN-LAST:event_opportunitybuttonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RegistrationPage rp= new RegistrationPage();
        rp.setVisible(true);
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorProfilePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel addresslabel;
    private javax.swing.JLabel age;
    private javax.swing.JLabel agelabel;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel background;
    private javax.swing.JPanel barpannel;
    private javax.swing.JPanel barpannel1;
    private javax.swing.JButton disabilitybutton;
    private javax.swing.JButton doctorbutton;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel genderlabel;
    private javax.swing.JLabel gototitle;
    private javax.swing.JLabel gototitle1;
    private javax.swing.JButton homebutton;
    private javax.swing.JButton hospitalbutton;
    private javax.swing.JLabel informationtitle;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel mobileno;
    private javax.swing.JLabel mobilenolabel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel namelabel;
    private javax.swing.JButton opportunitybutton;
    private javax.swing.JLabel patient;
    private javax.swing.JButton patientbutton;
    private javax.swing.JLabel title;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
