/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package care;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author SAIF
 */
public class DoctorSignInPage extends javax.swing.JFrame {

    /**
     * Creates new form DoctorSignInPage
     */
        Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public DoctorSignInPage() {
        initComponents();
        this.setLocationRelativeTo(null); //center form in the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        barpannel = new javax.swing.JPanel();
        doctor = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        signin = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        minimize = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("CARE  FOR  THE  SPECIAL  PEOPLE");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 670, 60));

        barpannel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout barpannelLayout = new javax.swing.GroupLayout(barpannel);
        barpannel.setLayout(barpannelLayout);
        barpannelLayout.setHorizontalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        barpannelLayout.setVerticalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(barpannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        doctor.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\IMG_4306.PNG")); // NOI18N
        doctor.setText("doctor");
        getContentPane().add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 100, 110));

        username.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        username.setForeground(new java.awt.Color(204, 255, 255));
        username.setText("USER NAME");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 100, 50));

        usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 210, -1));

        password.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        password.setForeground(new java.awt.Color(204, 255, 255));
        password.setText("PASSWORD");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 110, 50));
        getContentPane().add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 210, -1));

        signin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        signin.setForeground(new java.awt.Color(0, 102, 153));
        signin.setText("SIGN IN");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        getContentPane().add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 100, -1));

        exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(153, 255, 255));
        exit.setText("x");
        exit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, 30));

        backbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backbutton.setForeground(new java.awt.Color(0, 102, 153));
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, -1));

        minimize.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        minimize.setForeground(new java.awt.Color(153, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.setToolTipText("");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, 20));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\background_light_blur_68629_1920x1080.jpg")); // NOI18N
        background.setText("background");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefieldActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0); //for exit
    }//GEN-LAST:event_exitMouseClicked

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StartPage s = new StartPage();
        s.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);// for minimize
    }//GEN-LAST:event_minimizeMouseClicked

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        // TODO add your handling code here:
        
         conn = DatabaseHandler.connectDatabase1();   // connect with database - DatabaseHandler is a class name and connectDatabase1 is the method name situated in DatabaseHandler.java
            String sql = "SELECT * from doctor WHERE username =? and password=?";
            try{
                pst = conn.prepareStatement(sql);
                pst.setString(1, usernamefield.getText());
                pst.setString(2,passwordfield.getText());
                rs = pst.executeQuery();
                if(rs.next()){
                    String user = usernamefield.getText();
                    this.setVisible(false);
                    DoctorProfilePage dpp = new DoctorProfilePage(user); 
                    dpp.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Invalid username or password","Access Denied",JOptionPane.ERROR_MESSAGE);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
    }//GEN-LAST:event_signinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorSignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorSignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorSignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorSignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorSignInPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel background;
    private javax.swing.JPanel barpannel;
    private javax.swing.JLabel doctor;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JButton signin;
    private javax.swing.JLabel title;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
