/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package care;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SAIF
 */
public class DoctorHospitalPage1 extends javax.swing.JFrame {

    /**
     * Creates new form HospitalPage
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String user;
    public DoctorHospitalPage1() {
        initComponents();
        this.setLocationRelativeTo(null);
        //conn = DatabaseHandler.connectDatabase1();
        
        jTable1.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(String.class)).setBackground(new Color(0,0,0,0));
        
        jTable1.setGridColor(Color.WHITE);
        jTable1.setForeground(Color.WHITE);
        
        hospitalfield.setBackground(new Color(0,0,0,0));
        
        hospitalfield.setOpaque(false);
         jTable1.setOpaque(false);
            ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(String.class)).setOpaque(false);
            
        hospitalfield.getViewport().setOpaque(false);
        
        jTable1.setShowGrid(true);
        
        jTable1.setRowHeight(50);  //set rows height
        
      //  jTable1.setRowHeight(2,70);//sets height of a specific row
        
//sets column width
        TableColumnModel columnModel = jTable1.getColumnModel();
        TableModel model = jTable1.getModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(180);
        columnModel.getColumn(2).setPreferredWidth(3);
        columnModel.getColumn(3).setPreferredWidth(180);
        columnModel.getColumn(4).setPreferredWidth(40);
       show_info();
        
       // Update_table();
    }
    
    public DoctorHospitalPage1(String username) {
        this.user=username;
        initComponents();
        this.setLocationRelativeTo(null);
        //conn = DatabaseHandler.connectDatabase1();
        
        jTable1.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(String.class)).setBackground(new Color(0,0,0,0));
        
        jTable1.setGridColor(Color.WHITE);
        jTable1.setForeground(Color.WHITE);
        
        hospitalfield.setBackground(new Color(0,0,0,0));
        
        hospitalfield.setOpaque(false);
         jTable1.setOpaque(false);
            ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(String.class)).setOpaque(false);
            
        hospitalfield.getViewport().setOpaque(false);
        
        jTable1.setShowGrid(true);
        
        jTable1.setRowHeight(50);  //set rows height
        
      //  jTable1.setRowHeight(2,70);//sets height of a specific row
        
//sets column width
        TableColumnModel columnModel = jTable1.getColumnModel();
        TableModel model = jTable1.getModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(180);
        columnModel.getColumn(2).setPreferredWidth(3);
        columnModel.getColumn(3).setPreferredWidth(180);
        columnModel.getColumn(4).setPreferredWidth(40);
       show_info();
        
       // Update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homebutton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        hospitalfield = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        barpannel = new javax.swing.JPanel();
        searchbox = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        idfield = new javax.swing.JTextField();
        hospitalnamefield = new javax.swing.JTextField();
        phonefield = new javax.swing.JTextField();
        addressfield = new javax.swing.JTextField();
        cityfield = new javax.swing.JTextField();
        firstname = new javax.swing.JLabel();
        firstname1 = new javax.swing.JLabel();
        firstname2 = new javax.swing.JLabel();
        firstname3 = new javax.swing.JLabel();
        firstname4 = new javax.swing.JLabel();
        adddatabutton = new javax.swing.JButton();
        updatedatabutton = new javax.swing.JButton();
        deletedatabutton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        homebutton.setForeground(new java.awt.Color(0, 102, 153));
        homebutton.setText("HOME");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(homebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        title.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("CARE  FOR  THE  SPECIAL  PEOPLE");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 670, 60));

        minimize.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        minimize.setForeground(new java.awt.Color(153, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.setToolTipText("");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, 20));

        exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(153, 255, 255));
        exit.setText("x");
        exit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "HOSPITAL NAME", "PHONE", "ADDRESS", "CITY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                jTable1AncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        hospitalfield.setViewportView(jTable1);

        getContentPane().add(hospitalfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 890, 200));

        barpannel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout barpannelLayout = new javax.swing.GroupLayout(barpannel);
        barpannel.setLayout(barpannelLayout);
        barpannelLayout.setHorizontalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        barpannelLayout.setVerticalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(barpannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });
        getContentPane().add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 250, -1));

        searchbutton.setBackground(new java.awt.Color(204, 204, 255));
        searchbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(0, 102, 153));
        searchbutton.setText("SEARCH");
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, -1, -1));

        backbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backbutton.setForeground(new java.awt.Color(0, 102, 153));
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, -1, -1));

        idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfieldActionPerformed(evt);
            }
        });
        getContentPane().add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 210, -1));

        hospitalnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalnamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(hospitalnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 210, -1));

        phonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonefieldActionPerformed(evt);
            }
        });
        getContentPane().add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 210, -1));

        addressfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressfieldActionPerformed(evt);
            }
        });
        getContentPane().add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, 210, -1));

        cityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityfieldActionPerformed(evt);
            }
        });
        getContentPane().add(cityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 680, 210, -1));

        firstname.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        firstname.setForeground(new java.awt.Color(204, 255, 255));
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstname.setText("ID");
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 110, -1));

        firstname1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        firstname1.setForeground(new java.awt.Color(204, 255, 255));
        firstname1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstname1.setText("HOSPITAL NAME");
        getContentPane().add(firstname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 150, -1));

        firstname2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        firstname2.setForeground(new java.awt.Color(204, 255, 255));
        firstname2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstname2.setText("PHONE");
        getContentPane().add(firstname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 110, -1));

        firstname3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        firstname3.setForeground(new java.awt.Color(204, 255, 255));
        firstname3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstname3.setText("ADDRESS");
        getContentPane().add(firstname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 110, -1));

        firstname4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        firstname4.setForeground(new java.awt.Color(204, 255, 255));
        firstname4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstname4.setText("CITY");
        getContentPane().add(firstname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 680, 110, -1));

        adddatabutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adddatabutton.setForeground(new java.awt.Color(0, 102, 153));
        adddatabutton.setText("ADD DATA");
        adddatabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddatabuttonActionPerformed(evt);
            }
        });
        getContentPane().add(adddatabutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 160, -1));

        updatedatabutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        updatedatabutton.setForeground(new java.awt.Color(0, 102, 153));
        updatedatabutton.setText("UPDATE DATA");
        updatedatabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedatabuttonActionPerformed(evt);
            }
        });
        getContentPane().add(updatedatabutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, 160, -1));

        deletedatabutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        deletedatabutton.setForeground(new java.awt.Color(0, 102, 153));
        deletedatabutton.setText("DELETE DATA");
        deletedatabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedatabuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletedatabutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 160, -1));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\background_light_blur_68629_1920x1080.jpg")); // NOI18N
        background.setText("background");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<HospitalInfo> hospitalList(){
        ArrayList<HospitalInfo> hospitalsList = new ArrayList<>();
         conn = DatabaseHandler.connectDatabase1();
         try{
             String query = "SELECT * FROM hospital";
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(query);
             HospitalInfo info;
             while(rs.next()){
                 info = new HospitalInfo(rs.getInt("id"),rs.getString("name"),rs.getString("phone"),rs.getString("address"),rs.getString("city"));
                 hospitalsList.add(info);
             }
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
         return hospitalsList;
    }
    
    public void show_info(){
        ArrayList<HospitalInfo> list = hospitalList();
        DefaultTableModel model  = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[6];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getid();
            row[1] = list.get(i).getname();
            row[2] = list.get(i).getphone();
            row[3] = list.get(i).getaddress();
            row[4] = list.get(i).getcity();
            model.addRow(row);
        }
    }
    
   /* private void Update_table(){
        try{
            String sql = "SELECT * FROM hospital";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }*/
    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StartPage sp = new StartPage();
        sp.setVisible(true);
    }//GEN-LAST:event_homebuttonActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);// for minimize
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0); //for exit
    }//GEN-LAST:event_exitMouseClicked

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PatientProfilePage ppp= new PatientProfilePage(user);
        ppp.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void jTable1AncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTable1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorMoved

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
       String search =searchbox.getText();
       TableRowSorter<DefaultTableModel> tr = new  TableRowSorter<DefaultTableModel>(table);
       jTable1.setRowSorter(tr);
       tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_searchboxKeyReleased

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfieldActionPerformed

    private void hospitalnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalnamefieldActionPerformed

    private void phonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonefieldActionPerformed

    private void addressfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressfieldActionPerformed

    private void cityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityfieldActionPerformed

    private void adddatabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddatabuttonActionPerformed
        // TODO add your handling code here:
        try{
            String query = "INSERT into hospital(name,phone,address,city) values (?,?,?,?)";
            conn = DatabaseHandler.connectDatabase1();
            pst=conn.prepareStatement(query);
           // pst.setString(1,'namefield.getText());
           // pst.setString(1,'namefield.getText()){
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_adddatabuttonActionPerformed

    private void updatedatabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedatabuttonActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_updatedatabuttonActionPerformed

    private void deletedatabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedatabuttonActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_deletedatabuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorHospitalPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorHospitalPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorHospitalPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorHospitalPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorHospitalPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adddatabutton;
    private javax.swing.JTextField addressfield;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel background;
    private javax.swing.JPanel barpannel;
    private javax.swing.JTextField cityfield;
    private javax.swing.JButton deletedatabutton;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel firstname1;
    private javax.swing.JLabel firstname2;
    private javax.swing.JLabel firstname3;
    private javax.swing.JLabel firstname4;
    private javax.swing.JButton homebutton;
    private javax.swing.JScrollPane hospitalfield;
    private javax.swing.JTextField hospitalnamefield;
    private javax.swing.JTextField idfield;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField phonefield;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchbutton;
    private javax.swing.JLabel title;
    private javax.swing.JButton updatedatabutton;
    // End of variables declaration//GEN-END:variables
}
