/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package care;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author SAIF
 */
public class MedicalReportPage extends javax.swing.JFrame {

    /**
     * Creates new form MedicalReportPage
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
   /* JButton button ;
    JButton button2;
    JLabel label;
    JTextField id;
    JTextField name;
    JTextArea description;
    String s;*/
    public MedicalReportPage() {
        initComponents();
        this.setLocationRelativeTo(null);
   
        //super("insert image to database in java");
    /*
        button = new JButton("ADD");
        button.setBounds(200,300,100,40);
    
        button2 = new JButton("BROWSE");
        button2.setBounds(80, 300, 100, 40);
    
        id = new JTextField("ID");
        id.setBounds(320,290,100,20);

        name = new JTextField("Name");
        name.setBounds(320,330,100,20);

        description= new JTextArea("description",100, 100);
    
        JScrollPane pane = new JScrollPane(description);
        pane.setBounds(450, 270, 200, 100);
    
        label = new JLabel();
        label.setBounds(10,10,670,250);   

        //button to browse the image into jlabel
        button2.addActionListener(new ActionListener(){
        @Override
     public void actionPerformed(ActionEvent e){
         JFileChooser fileChooser = new JFileChooser();
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
             File selectedFile = fileChooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
             label.setIcon(ResizeImage(path));
             s = path;
              }
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("No Data");
         }
     }
    });
        
        //button to insert image and some data into mysql database
    button.addActionListener(new ActionListener(){
    
       @Override
       public void actionPerformed(ActionEvent e){
           try{
              // Connection con = DriverManager.getConnection("jdbc:mysql://localhost/db_images","root","");
              conn = DatabaseHandler.connectDatabase1();
              
               PreparedStatement ps = conn.prepareStatement("insert into medicalreport(id,name,description,image) values(?,?,?,?)");
               InputStream is = new FileInputStream(new File(s));
               ps.setString(1, idfield.getText());
               ps.setString(2, namefield.getText());
               ps.setString(3, descriptionfield.getText());
               ps.setBlob(4,is);
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null, "Data Inserted");
           }catch(Exception ex){
               ex.printStackTrace();
           }
       }
    });

    add(label);
    add(id);
    add(name);
    add(pane);
    add(button);
    add(button2);
    setLayout(null);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setSize(700,420);
    setVisible(true);
    */
    }
//Methode To Resize The ImageIcon
  /*  public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(labelfield.getWidth(), labelfield.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        barpannel = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        homebutton = new javax.swing.JButton();
        browsebutton = new javax.swing.JButton();
        showbutton = new javax.swing.JButton();
        opportunitybutton = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        idfield = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        addressfield = new javax.swing.JScrollPane();
        descriptionfield = new javax.swing.JTextArea();
        labelfield = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1230, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("CARE  FOR  THE  SPECIAL  PEOPLE");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 670, 60));

        barpannel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout barpannelLayout = new javax.swing.GroupLayout(barpannel);
        barpannel.setLayout(barpannelLayout);
        barpannelLayout.setHorizontalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        barpannelLayout.setVerticalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(barpannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        minimize.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        minimize.setForeground(new java.awt.Color(153, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.setToolTipText("");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, 20));

        exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(153, 255, 255));
        exit.setText("x");
        exit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, 30));

        homebutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        homebutton.setForeground(new java.awt.Color(0, 102, 153));
        homebutton.setText("HOME");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(homebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        browsebutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        browsebutton.setForeground(new java.awt.Color(0, 102, 153));
        browsebutton.setText("BROWSE");
        browsebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(browsebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 180, -1));

        showbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        showbutton.setForeground(new java.awt.Color(0, 102, 153));
        showbutton.setText("SHOW");
        showbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(showbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 180, -1));

        opportunitybutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        opportunitybutton.setForeground(new java.awt.Color(0, 102, 153));
        opportunitybutton.setText("OPPORTUNITY");
        opportunitybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opportunitybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(opportunitybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 510, 180, -1));

        addbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addbutton.setForeground(new java.awt.Color(0, 102, 153));
        addbutton.setText("ADD");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 180, -1));

        idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfieldActionPerformed(evt);
            }
        });
        getContentPane().add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 210, -1));

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 210, -1));

        descriptionfield.setColumns(20);
        descriptionfield.setRows(5);
        addressfield.setViewportView(descriptionfield);

        getContentPane().add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 210, 50));
        getContentPane().add(labelfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 450, 230));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\background_light_blur_68629_1920x1080.jpg")); // NOI18N
        background.setText("background");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);// for minimize
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0); //for exit
    }//GEN-LAST:event_exitMouseClicked

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StartPage sp = new StartPage();
        sp.setVisible(true);
    }//GEN-LAST:event_homebuttonActionPerformed

    private void browsebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebuttonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_browsebuttonActionPerformed

    private void showbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbuttonActionPerformed
        // TODO add your handling code here:
        
      /*  try{
            String sql = "Select image from medicalreport where id =1";
            pst = conn.prepareStatement(sql);
            rs= pst.executeQuery();
            if(rs.next()){
                byte[] imagedata = rs.getBytes("image");
                format = new ImageIcon(imagedata);
               // image.setIcon(format);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
     */
    }//GEN-LAST:event_showbuttonActionPerformed

    private void opportunitybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opportunitybuttonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_opportunitybuttonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_addbuttonActionPerformed

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfieldActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicalReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicalReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicalReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicalReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//new MedicalReportPage();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicalReportPage().setVisible(true);
                //new MedicalReportPage();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JScrollPane addressfield;
    private javax.swing.JLabel background;
    private javax.swing.JPanel barpannel;
    private javax.swing.JButton browsebutton;
    private javax.swing.JTextArea descriptionfield;
    private javax.swing.JLabel exit;
    private javax.swing.JButton homebutton;
    private javax.swing.JTextField idfield;
    private javax.swing.JLabel labelfield;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField namefield;
    private javax.swing.JButton opportunitybutton;
    private javax.swing.JButton showbutton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

private ImageIcon format = null;
}
