/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package care;
import java.sql.ResultSet;
import javax.swing.JFrame;

/**
 *
 * @author SAIF
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
        this.setLocationRelativeTo(null); //center form in the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barpannel = new javax.swing.JPanel();
        doctor = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        patient = new javax.swing.JLabel();
        others = new javax.swing.JLabel();
        patientbutton = new javax.swing.JButton();
        doctorbutton = new javax.swing.JButton();
        othersbutton = new javax.swing.JButton();
        createbutton = new javax.swing.JButton();
        title2 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barpannel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout barpannelLayout = new javax.swing.GroupLayout(barpannel);
        barpannel.setLayout(barpannelLayout);
        barpannelLayout.setHorizontalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        barpannelLayout.setVerticalGroup(
            barpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(barpannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        doctor.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\IMG_4302.PNG")); // NOI18N
        doctor.setText("doctor");
        getContentPane().add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 170, 180));

        title.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("CARE  FOR  THE  SPECIAL  PEOPLE");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, 60));

        patient.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\IMG_4301.PNG")); // NOI18N
        patient.setText("patient");
        getContentPane().add(patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 170, 180));

        others.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\IMG_4303.PNG")); // NOI18N
        others.setText("others");
        getContentPane().add(others, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 170, 180));

        patientbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        patientbutton.setForeground(new java.awt.Color(0, 102, 153));
        patientbutton.setText("PATIENT");
        patientbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(patientbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 140, -1));

        doctorbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        doctorbutton.setForeground(new java.awt.Color(0, 102, 153));
        doctorbutton.setText("DOCTOR");
        doctorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(doctorbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 140, -1));

        othersbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        othersbutton.setForeground(new java.awt.Color(0, 102, 153));
        othersbutton.setText("OTHERS");
        othersbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(othersbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, 140, -1));

        createbutton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        createbutton.setForeground(new java.awt.Color(0, 102, 153));
        createbutton.setText("CREATE  NEW  ACCOUNT");
        createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(createbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, -1, -1));

        title2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 36)); // NOI18N
        title2.setForeground(new java.awt.Color(204, 255, 204));
        title2.setText("SIGN  IN  AS");
        getContentPane().add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 240, 40));

        title3.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        title3.setForeground(new java.awt.Color(204, 255, 255));
        title3.setText("NEW USER  ?");
        getContentPane().add(title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 180, 30));

        exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(153, 255, 255));
        exit.setText("x");
        exit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, 30));

        minimize.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        minimize.setForeground(new java.awt.Color(153, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.setToolTipText("");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, 20));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAIF\\Desktop\\background_light_blur_68629_1920x1080.jpg")); // NOI18N
        background.setText("background");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PatientSignInPage p = new PatientSignInPage();
        p.setVisible(true);
        
       
        
    }//GEN-LAST:event_patientbuttonActionPerformed

    private void othersbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersbuttonActionPerformed
        // TODO add your handling code here:
        DatabaseHandler db = new DatabaseHandler();
        db.connectDatabase();
            
        this.setVisible(false);
        OthersSignInPage o = new OthersSignInPage();
        o.setVisible(true);
    }//GEN-LAST:event_othersbuttonActionPerformed

    private void createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbuttonActionPerformed
        // TODO add your handling code here:
        DatabaseHandler db = new DatabaseHandler();
        db.connectDatabase();
        
        this.setVisible(false);
        RegistrationPage r = new RegistrationPage();
        r.setVisible(true);
    }//GEN-LAST:event_createbuttonActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0); //for exit
    }//GEN-LAST:event_exitMouseClicked

    private void doctorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorbuttonActionPerformed
        // TODO add your handling code here:
        DatabaseHandler db = new DatabaseHandler();
        db.connectDatabase();
        this.setVisible(false);
        DoctorSignInPage d = new DoctorSignInPage();
        d.setVisible(true);
    }//GEN-LAST:event_doctorbuttonActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);// for minimize
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel barpannel;
    private javax.swing.JButton createbutton;
    private javax.swing.JLabel doctor;
    private javax.swing.JButton doctorbutton;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel others;
    private javax.swing.JButton othersbutton;
    private javax.swing.JLabel patient;
    private javax.swing.JButton patientbutton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    // End of variables declaration//GEN-END:variables
}
